metadata:
  id: prometheus
  name: Prometheus
  version: PTDL_v2
  game: generic
  author: p.zarrad@outlook.de
  description: The Prometheus monitoring system and time series database.
container:
  image: ghcr.io/parkervcp/yolks:debian
  environment: {}
resources:
  cpu:
    min: 1000
    max: 2000
    shares: 1024
  memory:
    min: 1Gi
    max: 2Gi
    swap: 512Mi
  disk:
    min: 5Gi
    io_priority: normal
startup:
  command: ./prometheus
  args:
  - --web.listen-address=0.0.0.0:{{SERVER_PORT}}
  - --config.file=/home/container/prometheus.yml
  - --storage.tsdb.path=/home/container/data
  - --web.console.templates=/home/container/consoles
  - --web.console.libraries=/home/container/console_libraries
  - --web.config.file=/home/container/prometheus.web.yml
  - --storage.tsdb.retention.time={{DATA_SAVE_TIME}}
  working_dir: /home/container
  lifecycle:
    pre_start: []
    post_start: []
    pre_stop:
    - type: execute
      command: ^C
      timeout: 30s
variables:
- name: PROMETHEUS_VERSION
  description: The version of Prometheus to install. By default the latest version is being installed.
  default: latest
  required: true
  secret: false
  user_editable: true
  user_viewable: true
- name: DATA_SAVE_TIME
  description: How long the data is being saved
  default: 15d
  required: true
  secret: false
  user_editable: true
  user_viewable: true
networking:
  ports: []
  dns:
  - 1.1.1.1
  - 1.0.0.1
security:
  capabilities:
    drop:
    - ALL
    add:
    - NET_BIND_SERVICE
  read_only_root: false
  no_new_privileges: true
  seccomp_profile: runtime/default
  firewall_rules:
  - type: connection_rate
    name: rate_limit_connections
    limit: 100/s
    action: drop
  - type: packet_size
    name: block_amplification
    max_size: 1500
    action: drop
