[package]
name = "egg-importer"
version = "0.1.0"
edition = "2021"

[dependencies]
game-config = { path = "../game-config" }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
thiserror.workspace = true
regex.workspace = true
tracing.workspace = true
